---
version: 2
project_name: helm-chart-bumper-action

before:
  hooks:
    - go test ./...

builds:
  - id: helm-chart-bumper
    main: ./cmd/helm-chart-bumper
    binary: helm-chart-bumper
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    format: tar.gz
    files:
      - README.md
      - action.yml

dockers_v2:
  - images:
      - ghcr.io/joejulian/actions/helm-chart-bumper-action
    tags:
      - "{{ .Version }}"
    platforms:
      - linux/amd64
      - linux/arm64

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
