---
name: "Helm chart bumper"
description: "Bump Helm Chart.yaml version based on appVersion/dependency semver changes"

inputs:
  base:
    description: "Path to base Chart.yaml to compare against"
    required: true
  cur:
    description: "Path to current Chart.yaml to bump"
    required: true
  write:
    description: "Whether to write changes back to the current Chart.yaml"
    required: false
    default: "false"

runs:
  using: "docker"
  image: "docker://ghcr.io/joejulian/actions/helm-chart-bumper-action:v0.0.4"
  args:
    - "--base"
    - "${{ inputs.base }}"
    - "--cur"
    - "${{ inputs.cur }}"
    - "${{ inputs.write == 'true' && '--write' || '' }}"

